### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Noreas** [kpa23/idle_codes#8]
![изображение](https://user-images.githubusercontent.com/23726199/141312077-d787f6b5-c1c6-4603-8f5e-6f97543e6344.png)

PS C:\Windows\system32> java -jar J:\Games\IdleChampionAuto\idlecodes-1.3.jar
------Last 20 codes saved------
-------------------------------
New codes:
Code is copied to the clipboard
XLCS-EMDN-YZZMException in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:222)
        at com.idlecodes.CodeBot$User32.<clinit>(CodeBot.java:108)
        at com.idlecodes.CodeBot.<init>(CodeBot.java:122)
        at com.idlecodes.IdleCodes.autoCode(IdleCodes.java:45)
        at com.idlecodes.IdleCodes.main(IdleCodes.java:93)

PS C:\Windows\system32> java -jar J:\Games\IdleChampionAuto\idlecodes-1.2.jar
------Last 20 codes saved------
-------------------------------
New codes:
Code is copied to clipboard
XLCS-EMDN-YZZMCan't find "Unlock a Locked Chest" button. Make sure the game is opened.

**Comment by kpa23** [comment]
Thanks! working on it. Need a few changes. New version will be available soon

**Comment by kpa23** [comment]
fixed in  https://github.com/kpa23/idle_codes/releases/tag/0.1.4
