### ISSUE TITLE
java version

### ISSUE THREAD

**Issue by JensGrote** [kpa23/idle_codes#9]
I use openJDK or java 8 as last non commercial version - this does not seem to run with that.

C:\temp\Idlecodes>java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

C:\temp\Idlecodes>java -jar idlecodes-1.1.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/idlecodes/IdleCodes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

C:\temp\Idlecodes>

**Comment by kpa23** [comment]
Yeah, I saw it already on another PC. I'm new to java and I'll try to figure out this version support system in a few days. Thanks for testing. As a workaround JDK17 from oracle.com works, but I'll try to recompile it for that version you mentioned.

**Comment by kpa23** [comment]
Lowered the version of needed Java to 53.0. 
Can't compile to 52.0, cause no support on streams that I needed.
If you can easy rewrite this for java 1.8 (v52.0), I would be happy to accept pull request.
```
String[] matches = Pattern.compile("(?<=\\\")([\\w!@#$%^&*.]{4}-?){2,3}([\\w!@#$%^&*.]{4})(?=\\\\)")
                .matcher(data)
                .results()
                .map(MatchResult::group)
                .toArray(String[]::new);
```
Or use JDK of newer version instead of old JRE.
